---

- name: Install nginx
  apt:
    pkg: nginx
    update_cache: yes
    state: latest

- name: Apply nginx configuration
  notify: restart nginx
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
    force: yes
