---

- name: Configure the server
  sudo: yes
  hosts:
    - tag_osp_search

  vars_files:
    - vars/elasticsearch.yml
    - vars/postgres.yml

  roles:
    - common
    - postgres
    - elasticsearch
    - nginx
    - nodejs
