---

postgresql_version: 9.4
postgresql_data_directory: /osp/data/postgresql
postgresql_client_encoding: utf8
postgresql_ext_install_contrib: yes

postgresql_databases:
  - name: '{{ pg_db }}'

postgresql_users:
  - name: '{{ pg_user }}'
    pass: '{{ pg_pass }}'

postgresql_user_privileges:
  - name: '{{ pg_user }}'
    db: '{{ pg_db }}'
    priv: 'ALL'
