---

postgresql_version: 9.4
postgresql_data_directory: /osp/data/postgresql
postgresql_ext_install_contrib: yes
postgresql_max_connections: 500
postgresql_client_encoding: utf8

postgresql_listen_addresses:
  - '*'

postgresql_pg_hba_custom:
  - type: host
    database: '{{ pg_pass }}'
    user: all
    address: all
    method: md5
    comment: ''

postgresql_databases:
  - name: '{{ pg_db }}'
    hstore: yes

postgresql_users:
  - name: '{{ pg_user }}'
    pass: '{{ pg_pass }}'

postgresql_user_privileges:
  - name: '{{ pg_user }}'
    db: '{{ pg_db }}'
    priv: 'ALL'

