---

postgresql_version: 9.4
postgresql_data_directory: /osp/data/postgresql
postgresql_ext_install_contrib: yes
postgresql_client_encoding: utf8
postgresql_max_connections: 500

postgresql_listen_addresses:
  - '*'

postgresql_pg_hba_custom:
  - type: host
    database: osp
    user: all
    address: all
    method: md5
    comment: ''

postgresql_databases:
  - name: osp
    hstore: yes

postgresql_users:
  - name: osp

postgresql_user_privileges:
  - name: osp
    db: osp
    priv: 'ALL'
